# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 340)
        MainWindow.setMinimumSize(QtCore.QSize(710, 340))
        MainWindow.setMaximumSize(QtCore.QSize(710, 340))
        MainWindow.setDocumentMode(True)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 511, 261))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 40, 241, 211))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.primary_brightness = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.primary_brightness.setProperty("value", 99)
        self.primary_brightness.setOrientation(QtCore.Qt.Vertical)
        self.primary_brightness.setObjectName("primary_brightness")
        self.horizontalLayout_2.addWidget(self.primary_brightness)
        self.primary_red = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.primary_red.setProperty("value", 99)
        self.primary_red.setOrientation(QtCore.Qt.Vertical)
        self.primary_red.setObjectName("primary_red")
        self.horizontalLayout_2.addWidget(self.primary_red)
        self.primary_green = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.primary_green.setProperty("value", 99)
        self.primary_green.setOrientation(QtCore.Qt.Vertical)
        self.primary_green.setObjectName("primary_green")
        self.horizontalLayout_2.addWidget(self.primary_green)
        self.primary_blue = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.primary_blue.setProperty("value", 99)
        self.primary_blue.setOrientation(QtCore.Qt.Vertical)
        self.primary_blue.setObjectName("primary_blue")
        self.horizontalLayout_2.addWidget(self.primary_blue)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 40, 241, 211))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.secondary_brightness = QtWidgets.QSlider(self.horizontalLayoutWidget_3)
        self.secondary_brightness.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.secondary_brightness.setProperty("value", 99)
        self.secondary_brightness.setOrientation(QtCore.Qt.Vertical)
        self.secondary_brightness.setObjectName("secondary_brightness")
        self.horizontalLayout_3.addWidget(self.secondary_brightness)
        self.secondary_red = QtWidgets.QSlider(self.horizontalLayoutWidget_3)
        self.secondary_red.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.secondary_red.setProperty("value", 99)
        self.secondary_red.setOrientation(QtCore.Qt.Vertical)
        self.secondary_red.setObjectName("secondary_red")
        self.horizontalLayout_3.addWidget(self.secondary_red)
        self.secondary_green = QtWidgets.QSlider(self.horizontalLayoutWidget_3)
        self.secondary_green.setProperty("value", 99)
        self.secondary_green.setOrientation(QtCore.Qt.Vertical)
        self.secondary_green.setObjectName("secondary_green")
        self.horizontalLayout_3.addWidget(self.secondary_green)
        self.secondary_blue = QtWidgets.QSlider(self.horizontalLayoutWidget_3)
        self.secondary_blue.setProperty("value", 99)
        self.secondary_blue.setOrientation(QtCore.Qt.Vertical)
        self.secondary_blue.setObjectName("secondary_blue")
        self.horizontalLayout_3.addWidget(self.secondary_blue)
        self.horizontalLayout.addWidget(self.groupBox)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(13, 260, 77, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(100, 260, 21, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(150, 260, 21, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(200, 260, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(281, 260, 77, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(370, 260, 21, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(420, 260, 21, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(470, 260, 16, 16))
        self.label_8.setObjectName("label_8")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(529, 0, 213, 218))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 11, 0, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.primary_combobox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.primary_combobox.sizePolicy().hasHeightForWidth())
        self.primary_combobox.setSizePolicy(sizePolicy)
        self.primary_combobox.setMaximumSize(QtCore.QSize(150, 28))
        self.primary_combobox.setObjectName("primary_combobox")
        self.verticalLayout.addWidget(self.primary_combobox)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.secondary_combo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.secondary_combo.setMaximumSize(QtCore.QSize(150, 28))
        self.secondary_combo.setObjectName("secondary_combo")
        self.verticalLayout.addWidget(self.secondary_combo)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setMaximumSize(QtCore.QSize(150, 28))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.FocusViewBox = QtWidgets.QCheckBox(self.centralWidget)
        self.FocusViewBox.setEnabled(True)
        self.FocusViewBox.setGeometry(QtCore.QRect(533, 220, 101, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FocusViewBox.sizePolicy().hasHeightForWidth())
        self.FocusViewBox.setSizePolicy(sizePolicy)
        self.FocusViewBox.setAutoFillBackground(True)
        self.FocusViewBox.setChecked(False)
        self.FocusViewBox.setAutoRepeat(False)
        self.FocusViewBox.setObjectName("FocusViewBox")
        self.FocusLabel = QtWidgets.QLabel(self.centralWidget)
        self.FocusLabel.setEnabled(False)
        self.FocusLabel.setGeometry(QtCore.QRect(533, 249, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.FocusLabel.setFont(font)
        self.FocusLabel.setProperty("Enable", False)
        self.FocusLabel.setObjectName("FocusLabel")
        self.FocusViewFrame = QtWidgets.QFrame(self.centralWidget)
        self.FocusViewFrame.setEnabled(True)
        self.FocusViewFrame.setGeometry(QtCore.QRect(523, 230, 171, 51))
        self.FocusViewFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FocusViewFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FocusViewFrame.setObjectName("FocusViewFrame")
        self.FocusDimPr = QtWidgets.QSpinBox(self.FocusViewFrame)
        self.FocusDimPr.setEnabled(False)
        self.FocusDimPr.setGeometry(QtCore.QRect(111, 16, 51, 26))
        self.FocusDimPr.setSpecialValueText("")
        self.FocusDimPr.setSuffix("%")
        self.FocusDimPr.setPrefix("")
        self.FocusDimPr.setMinimum(0)
        self.FocusDimPr.setMaximum(100)
        self.FocusDimPr.setProperty("value", 70)
        self.FocusDimPr.setObjectName("FocusDimPr")
        self.FocusViewFrame.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.verticalLayoutWidget.raise_()
        self.FocusViewBox.raise_()
        self.FocusLabel.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 710, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLicense = QtWidgets.QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setVisible(True)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setVisible(True)
        self.actionLoad.setObjectName("actionLoad")
        self.actionCheck_for_update = QtWidgets.QAction(MainWindow)
        self.actionCheck_for_update.setEnabled(False)
        self.actionCheck_for_update.setObjectName("actionCheck_for_update")
        self.actionDefault = QtWidgets.QAction(MainWindow)
        self.actionDefault.setObjectName("actionDefault")
        self.actionClearDefault = QtWidgets.QAction(MainWindow)
        self.actionClearDefault.setVisible(False)
        self.actionClearDefault.setObjectName("actionClearDefault")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionDefault)
        self.menuFile.addAction(self.actionClearDefault)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionLicense)
        self.menuHelp.addAction(self.actionCheck_for_update)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.FocusViewBox.clicked['bool'].connect(self.FocusLabel.setEnabled)
        self.FocusViewBox.clicked['bool'].connect(self.FocusDimPr.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Brightness Controller"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Primary"))
        self.groupBox.setTitle(_translate("MainWindow", "Secondary"))
        self.label.setText(_translate("MainWindow", "Brightness"))
        self.label_2.setText(_translate("MainWindow", " R"))
        self.label_3.setText(_translate("MainWindow", " G"))
        self.label_4.setText(_translate("MainWindow", " B"))
        self.label_5.setText(_translate("MainWindow", "Brightness"))
        self.label_6.setText(_translate("MainWindow", " R"))
        self.label_7.setText(_translate("MainWindow", " G"))
        self.label_8.setText(_translate("MainWindow", " B"))
        self.label_9.setText(_translate("MainWindow", "Advanced"))
        self.label_12.setText(_translate("MainWindow", "Primary Brightness"))
        self.label_11.setText(_translate("MainWindow", "Secondary Brightness"))
        self.secondary_combo.setToolTip(_translate("MainWindow", "<html><head/><body><p>You can select the source of Secondary Brightness Here.</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Color Temperature"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Default"))
        self.comboBox.setItemText(1, _translate("MainWindow", "1900K Candle"))
        self.comboBox.setItemText(2, _translate("MainWindow", "2600K 40W Tungsten"))
        self.comboBox.setItemText(3, _translate("MainWindow", "2850K 100W Tungsten"))
        self.comboBox.setItemText(4, _translate("MainWindow", "3200K Halogen"))
        self.comboBox.setItemText(5, _translate("MainWindow", "5200K Carbon Arc"))
        self.comboBox.setItemText(6, _translate("MainWindow", "5400K High Noon"))
        self.comboBox.setItemText(7, _translate("MainWindow", "6000K Direct Sun"))
        self.comboBox.setItemText(8, _translate("MainWindow", "7000K Overcast Sky"))
        self.comboBox.setItemText(9, _translate("MainWindow", "20000K Clear Blue Sky"))
        self.FocusViewBox.setText(_translate("MainWindow", "Focus View"))
        self.FocusLabel.setText(_translate("MainWindow", "Focus Dimming %"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.actionExit.setText(_translate("MainWindow", "E&xit"))
        self.actionHelp.setText(_translate("MainWindow", "&Help"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.actionLicense.setText(_translate("MainWindow", "&License"))
        self.actionSave.setText(_translate("MainWindow", "&Save current settings"))
        self.actionLoad.setText(_translate("MainWindow", "&Load settings"))
        self.actionCheck_for_update.setText(_translate("MainWindow", "&Check for Update"))
        self.actionDefault.setText(_translate("MainWindow", "Save current as default"))
        self.actionClearDefault.setText(_translate("MainWindow", "&Clear default settings"))
